# Generated by Django 4.2.4 on 2023-08-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_users_avatar_posts_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
