# Generated by Django 4.2.4 on 2023-08-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_rename_user_id_posts_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.users')),
            ],
        ),
    ]
