# Generated by Django 4.2.4 on 2023-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_users_options_alter_users_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
