# Generated by Django 4.2.4 on 2023-08-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_avatars_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='posts',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Avatars',
        ),
    ]
